clear all
close all 
clc

%% Create a GUI window 
window = figure('position',[0 0 800 800],...
                'unit','pixels',...
                'name','Sudoko Solver',...
                'visible','on');
movegui(window,'center')
%% Create my Sudoku cells
CornerX = 150;
CornerY = 600;
dx = 55;
dy = 55;
for ii = 1:9
    for jj = 1:9
        xPos = CornerX + (jj-1)*dx;
        yPos = CornerY - (ii-1)*dy; 
        sudokugui.X(ii,jj) = uicontrol('unit','pixels',...
                                       'background','w',...
                                       'Style','edit',...
                                       'visible','on',...
                                       'position',[xPos,yPos,dx dy],...
                                       'fontsize',14',...
                                       'fontweight','normal',...
                                       'enable','on',...
                                       'KeyPressFcn',{@cbEntry,window,ii,jj});
    end
end
%% Insert a title textbox
sudokugui.title = uicontrol('Style','text',...  
                            'unit','pixels',...
                            'Fontweight','normal',...   
                            'string','Sudoku Solver',...
                            'Position',[150 700 495 50],...
                            'FontSize',24,...
                            'backgroundcolor',[0.2 0.7 0.7],...
                            'foregroundcolor',[1 1 0]);
%% Insert a SOLVE button
sudokugui.solve = uicontrol('Style','pushbutton',...
                            'callback',{@cbSolve,window},...
                            'string','Solve',...
                            'position',[535 115 110 35],...
                            'backgroundcolor',[0.2 0 0.7],...
                            'foregroundcolor',[0.2 0.9 0]);

%% Insert a CLEAR button
sudokugui.clear = uicontrol('Style','pushbutton',...
                            'callback',{@cbClear,window},...
                            'string','Clear',...
                            'position',[535 80 110 35],...
                            'backgroundcolor',[0.9 0.1 0.2],...
                            'foregroundcolor',[1 0.9 0]);
%% Insert a status bar
sudokugui.status = uicontrol('Style','text',...
                             'unit','pixels',...
                             'string','Sudoku solver create by group 1!',...
                             'backgroundcolor',[0.7 0.8 0.7],...
                             'Fontsize',12,...
                             'Position',[150 80 385 70],...
                             'Horizontalalignment','left');
set(window,'UserData',sudokugui)
